
# This file was *autogenerated* from the file ./jacob.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/bin/env sage

from sage.all import *

Q = QuaternionAlgebra(SR, -_sage_const_1 , -_sage_const_1 , names=('i', 'j', 'k',)); (i, j, k,) = Q._first_ngens(3)

var('q0, q1, q2, q3')
var('dt')
var('wx, wy, wz')

q = q0 + q1*i + q2*j + q3*k

w = vector([wx, wy, wz])*dt
w_norm = sqrt(w[_sage_const_0 ]**_sage_const_2  + w[_sage_const_1 ]**_sage_const_2  + w[_sage_const_2 ]**_sage_const_2 )
ang = w_norm/_sage_const_2 
w_normalized = w/w_norm
sin2 = sin(ang)
qd = cos(ang) + w_normalized[_sage_const_0 ]*sin2*i + w_normalized[_sage_const_1 ]*sin2*j + w_normalized[_sage_const_2 ]*sin2*k

nq = q*qd

#v = vector(nq.coefficient_tuple()).column()
v = vector(nq.coefficient_tuple())

for sym in [wx, wy, wz, q0, q1, q2, q3]:
    d = diff(v, sym)
    exps = map(lambda x: x.canonicalize_radical().full_simplify(), d)
    for i, e in enumerate(exps):
        print(sym, i, e) 
#ds = d.map(lambda x: x

